add_newline = false

[character]      
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"
# vicmd_symbol = "[â®](bold white)"
vicmd_symbol = "[N](bold white)"

[package]
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = false
threshold = 75

[status]
# style = "bg:blue"
symbol = "ğŸ”´"
format = '[\[$symbol$signal_number $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
pipestatus = false
disabled = false
